version: '3'
services:
  langchain-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchaing-server
    ports:
      - 8010:8501
    volumes:
      - .:/home
    environment:
      - APP_ENV=${APP_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command:  streamlit run app.py
    networks:
      - langchain

networks:
  langchain:
